---
format: revealjs
title: thanks, i made it in quartodoc ðŸ¤
slide-number: true
---

# just a python developer, trying to make a docs site

::: notes
and you really want 2 things in a docs site, api docs and long format documentation
:::

# api 

# long format

# makedocs 
bed was too soft: felt nice, but unable to do the things to give user's the documentation you need (API documentation)

# sphinx
bed was too hard: feels like you have to be a sphinx developer to write sphinx docs, difficult to get going, who even wants to write rst ðŸ˜©

# quartodoc
builds API docs to put inside a quarto site

## vetiver

## pins

# developer wins

## quick to get started

## maintainable, literate config
- feels like bullet points

## built off quarto
- extensible as packages grow
- built with ergonomics in mind

# user wins

## predictable
- pkgdown is well loved in R community bc of its predictability & straightforward structure
- story of R -> Python

## built in accessibility due to quarto build
    
## wasm elements
- https://shiny.posit.co/py/api/ui.update_numeric.html#shiny.ui.update_numeric

# conclusion
- hospitality story
- made w <3 and quarto

